require: rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - vendor/**/*
  TargetRubyVersion: 2.5
  DisplayCopNames: true

Rails:
  Enabled: true

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - spec/**/*'

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*
